config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2"]
        no_follow_redirects: false
        preferred_ip_protocol: "ip4"
        ip_protocol_fallback: false

serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  ## https://github.com/coreos/prometheus-operator
  ##
  enabled: true

  # Default values that will be used for all ServiceMonitors created by `targets`
  defaults:
    labels: {}
    interval: 5s
    scrapeTimeout: 5s
    module: http_2xx

  targets:
    - name: example                    # Human readable URL that will appear in Prometheus / AlertManager
      url: http://www.heise.de/        # The URL that blackbox will scrape
